### PR TITLE
Release v0.1

### PR DESCRIPTION
**Pull request by srri-zz**
This is the pull request to stage v0.1 for release (merging back to master)
@psiemens @blx comment here when you think it's ready to merge back. 
Criteria:
- All known bugs are fixed
- Travis marks the build as successful and tests pass
- More tests added.

### CODE REVIEW

**Comment by psiemens** [comment]
Just working on adding more tests and comments to the code -- then it should be good to go.

**Comment by srri-zz** [comment]
Got those tests added, let me know when I can merge.

**Comment by psiemens** [comment]
Looks good to me. Probably _could_ use more tests, but I think it's okay to go ahead and call it v 0.1. Ship it!

**Comment by srri-zz** [comment]
Shipping!

**Pull request merged**
