### PR TITLE
Bug/embeds rendering

### PR DESCRIPTION
**Pull request by jordanschalm**

### CODE REVIEW

**Comment by jordanschalm** [comment]
Yeah that's a better solution. Not sure about that error because all the render methods should have accepted two parameters self & data.

**Comment by blx** [comment]
Yeah, I think the thing is just that -- please correct me if I'm wrong -- previously `self` would have been implicitly provided since it was a normal method, and the same thing for classmethods, it's just that static methods don't get any implicit first param.

**Comment by blx** [comment]
But you weren't getting any errors? hmm.

**Comment by jordanschalm** [comment]
Yeah I'm actually curious to see where your error came from, it looked like it was hitting a render method with only one parameter, but there shouldn't have been any of those in embeds.py

**Comment by jordanschalm** [comment]
Regardless I think it's better for the render methods to be class methods

**Comment by blx** [comment]
Ah! It was choking on rendering an `image`, which still had only one param https://github.com/ubyssey/dispatch/blob/1d5d2af6ef88a7fc17564896f0aaf80af43363ef/dispatch/apps/content/models.py#L796

```
Traceback:
File "/Users/ben/projects/2dispatch/env/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/ben/projects/2dispatch/dispatch/themes/ubyssey/views.py" in article
  103.         return HttpResponse(t.render(context))
File "/Users/ben/projects/2dispatch/env/lib/python2.7/site-packages/django/template/backends/django.py" in render
  74.         return self.template.render(context)
File "/Users/ben/projects/2dispatch/env/lib/python2.7/site-packages/django/template/base.py" in render
  209.                     return self._render(context)
File "/Users/ben/projects/2dispatch/env/lib/python2.7/site-packages/django/template/base.py" in _render
  201.         return self.nodelist.render(context)
File "/Users/ben/projects/2dispatch/env/lib/python2.7/site-packages/django/template/base.py" in render
  903.                 bit = self.render_node(node, context)
File "/Users/ben/projects/2dispatch/env/lib/python2.7/site-packages/django/template/base.py" in render_node
  917.         return node.render(context)
File "/Users/ben/projects/2dispatch/env/lib/python2.7/site-packages/django/template/loader_tags.py" in render
  135.         return compiled_parent._render(context)
File "/Users/ben/projects/2dispatch/env/lib/python2.7/site-packages/django/template/base.py" in _render
  201.         return self.nodelist.render(context)
File "/Users/ben/projects/2dispatch/env/lib/python2.7/site-packages/django/template/base.py" in render
  903.                 bit = self.render_node(node, context)
File "/Users/ben/projects/2dispatch/env/lib/python2.7/site-packages/django/template/base.py" in render_node
  917.         return node.render(context)
File "/Users/ben/projects/2dispatch/env/lib/python2.7/site-packages/django/template/loader_tags.py" in render
  65.                 result = block.nodelist.render(context)
File "/Users/ben/projects/2dispatch/env/lib/python2.7/site-packages/django/template/base.py" in render
  903.                 bit = self.render_node(node, context)
File "/Users/ben/projects/2dispatch/env/lib/python2.7/site-packages/django/template/base.py" in render_node
  917.         return node.render(context)
File "/Users/ben/projects/2dispatch/env/lib/python2.7/site-packages/django/template/base.py" in render
  957.             output = self.filter_expression.resolve(context)
File "/Users/ben/projects/2dispatch/env/lib/python2.7/site-packages/django/template/base.py" in resolve
  647.                 obj = self.var.resolve(context)
File "/Users/ben/projects/2dispatch/env/lib/python2.7/site-packages/django/template/base.py" in resolve
  787.             value = self._resolve_lookup(context)
File "/Users/ben/projects/2dispatch/env/lib/python2.7/site-packages/django/template/base.py" in _resolve_lookup
  847.                             current = current()
File "/Users/ben/projects/2dispatch/dispatch/apps/content/models.py" in get_html
  186.             return prepare_html(json.loads(self.content))
File "/Users/ben/projects/2dispatch/dispatch/apps/content/models.py" in prepare_html
  178.                     html += embedlib.render(node['type'], node['data'])
File "/Users/ben/projects/2dispatch/dispatch/apps/frontend/embeds.py" in render
  23.             return self.library[type].render(self.library[type], data)

Exception Type: TypeError at /culture/culture-af/
Exception Value: render() takes exactly 1 argument (2 given)
```

**Comment by jordanschalm** [comment]
Ah that makes sense

**Pull request merged**
