### PR TITLE
Refactoring Dispatch as standalone package

### PR DESCRIPTION
**Pull request by psiemens**
**Work in progress**

Until now Dispatch has been structured in way that's similar to WordPress, where user content (themes, static files, media) live inside of the main project directory. This worked when we were only powering ubyssey.ca, but now that the platform is also being used by sfalta.com, it's becoming increasingly hard to share code between the two projects. 

The refactor aims to produce a standalone Python package than can be installed (and updated) independently from a user's code and imported as needed (think `pip install dispatch`). This decoupling will allow users to focus on theme development while we worry about all of the super secret internal stuff without stepping on anybody's toes. 

Feedback appreciated!

cc @blx @jordanschalm

### CODE REVIEW

**Comment by blx** [comment]
This is an excellent thing to which i can't give a comprehensive review right now, especially considering it's not done yet. But yes, agreed.

**Comment by jordanschalm** [comment]
This is a really good idea

**Comment by psiemens** [comment]
@blx @jordanschalm @willmcdonald Glad you guys support this! 

Can you do me a favour and follow the instructions in https://github.com/ubyssey/dispatch/blob/project-structure-refactor/README.md and see if you can get the starter project running in your local environment? I'm curious to see how well it works on other machines.

**Comment by blx** [comment]
@psiemens Things I ran into on a fresh DO box, running Ubuntu 14.04 and a virtualenv:

```
(.env)$ python setup.py develop

  ...
  File "/tmp/easy_install-hcaNmq/Pillow-3.1.1/setup.py", line 516, in build_extensions

ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
```

I installed libjpeg with `sudo apt-get install libjpeg-dev`.

```
  File "/tmp/easy_install-QY6VJ5/Pillow-3.1.1/setup.py", line 519, in build_extensions

ValueError: --enable-zlib requested but zlib not found, aborting.
```

I installed zlib with `sudo apt-get install zlib1g-dev`.

```
Running Pillow-3.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-80olfm/Pillow-3.1.1/egg-dist-tmp-PmYkI2
Single threaded build, not installing mp_compile:1 processes
warning: no previously-included files found matching '.editorconfig'
_imaging.c:76:20: fatal error: Python.h: No such file or directory
 #include "Python.h"
                    ^
compilation terminated.
```

I ran `sudo apt-get install python-dev`.

```
  File "/tmp/easy_install-Jq8ozW/MySQL-python-1.2.5/setup_posix.py", line 43, in get_config
  File "/tmp/easy_install-Jq8ozW/MySQL-python-1.2.5/setup_posix.py", line 25, in mysql_config
EnvironmentError: mysql_config not found
```

I ran `sudo apt-get install libmysqlclient-dev`.

`python setup.py develop` now succeeded.

I tried to runserver, but first had to install and configure mysql:

``` shell
$ sudo apt-get install mysql-server     # with no root password
$ mysql
mysql> create database dispatch;
```

After that it seems to run! Will try to test some more in the next few days.

**Comment by psiemens** [comment]
@blx Awesome, thanks! 

The whole `libjpeg` thing is a known issue that I think can be solved by using a specific version of Pillow -- I'll look into that. 

Totally forgot about the database stuff -- oops. I plan to add a project-specific `settings.py` that will include database config and other goodies.

**Comment by jordanschalm** [comment]
I'll probably be able to run through this tomorrow

**Comment by willmcdonald** [comment]
@psiemens worked for me in a virtualenv in OS X 10.11!

**Comment by jordanschalm** [comment]
Works for me in 10.11 as well :tada:

**Pull request merged**
