### PR TITLE
modified content tests to include author

### PR DESCRIPTION
**Pull request by psiemens**
I added an author parameter to the article test now that the author field is implemented. This is a fix for the issue discussed in #37 -- the author field no longer has to be commented out.

### CODE REVIEW

**Comment by srri-zz** [comment]
Alt text

**Comment by psiemens** [comment]
I know I know. It's not detecting my change to the models file. Build is failing because author is still commented out. Just hang on a sec

**Comment by srri-zz** [comment]
Haha I'm just kidding around

**Comment by psiemens** [comment]
Haha I know

**Comment by psiemens** [comment]
THERE WE GO

**Comment by srri-zz** [comment]
Ship it!

alt text

**Pull request merged**
