### PR TITLE
Add science links everywhere, fix article formatting, reading list sorting

### PR DESCRIPTION
**Pull request by jordanschalm**

### CODE REVIEW

**Comment by psiemens** [comment]
:+1:

**Comment by jordanschalm** [comment]
We're actually going to wait until tomorrow to launch science so don't merge yet

**Comment by psiemens** [comment]
No I want science NOW!

**Comment by jordanschalm** [comment]
You wrote a _very_ nice article about science on the dev server

**Comment by blx** [comment]
Since this is HTML not python it doesn't matter, but the only thing I did notice in the diff is mixing tabs and spaces.

I don't wanna be the tabs vs spaces guy but we might as well try to stick to one format.

**Pull request merged**
